name: âš½ Update Data
on:
  schedule:
    - cron: 0 8 * FEB-OCT MON
    - cron: 0 8 * FEB-OCT THU
    - cron: 0 8 * FEB-OCT SUN
  workflow_dispatch: ~
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: 3.13
      - name: Set up uv and install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync
      - name: Run update script
        run: uv run .github/workflows/update.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: |
            data: update
          branch: auto-update
          title: Update data
          reviewers: bgrnwd